In [21]:
import sklearn as sk
import matplotlib as plt
import pandas as pd


# Use read_csv() to load the CSV file into a pandas DataFrame
data = pd.read_csv('Data/full_data.csv',low_memory=False)
data.drop('Unnamed: 0', axis = 1, inplace = True)
data

,lastTradeDate,strike,price,bid,ask,change,percentChange,volume,openInterest,sigma,...,returnOnAssets,returnOnEquity,freeCashflow,operatingCashflow,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,tau,tau2
0,2024-03-08,210.0,199.70,417.49,418.06,0.000000,0.000000,19275689.0,0.0,0.223118,...,0.15190,0.39174,5.868100e+10,1.026470e+11,0.176,0.69815,0.52037,0.43586,0.055556,0.054795
1,2024-03-27,220.0,200.32,417.49,418.06,-9.569992,-4.559527,19275689.0,2.0,0.223118,...,0.15190,0.39174,5.868100e+10,1.026470e+11,0.176,0.69815,0.52037,0.43586,0.003968,0.002740
2,2024-03-27,230.0,189.90,417.49,418.06,1.399994,0.742702,19275689.0,3.0,0.223118,...,0.15190,0.39174,5.868100e+10,1.026470e+11,0.176,0.69815,0.52037,0.43586,0.003968,0.002740
3,2024-02-13,235.0,174.91,417.49,418.06,0.000000,0.000000,19275689.0,6.0,0.223118,...,0.15190,0.39174,5.868100e+10,1.026470e+11,0.176,0.69815,0.52037,0.43586,0.126984,0.120548
4,2024-03-27,250.0,170.23,417.49,418.06,-9.120010,-5.085035,19275689.0,6.0,0.223118,...,0.15190,0.39174,5.868100e+10,1.026470e+11,0.176,0.69815,0.52037,0.43586,0.003968,0.002740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73149,2024-01-10,2.0,0.05,1.71,2.34,0.000000,0.000000,124821.0,1382.0,1.064334,...,-0.10972,0.10401,2.431477e+08,5.283660e+08,-0.425,0.03447,-0.18544,-0.18645,0.365079,0.350685
73150,2023-11-16,3.0,0.15,1.71,2.34,0.000000,0.000000,124821.0,12.0,1.064334,...,-0.10972,0.10401,2.431477e+08,5.283660e+08,-0.425,0.03447,-0.18544,-0.18645,0.519841,0.501370
73151,2023-09-19,4.0,0.16,1.71,2.34,0.000000,0.000000,124821.0,1.0,1.064334,...,-0.10972,0.10401,2.431477e+08,5.283660e+08,-0.425,0.03447,-0.18544,-0.18645,0.686508,0.660274
73152,2023-12-06,1.0,0.25,1.71,2.34,0.000000,0.000000,124821.0,1.0,1.064334,...,-0.10972,0.10401,2.431477e+08,5.283660e+08,-0.425,0.03447,-0.18544,-0.18645,0.464286,0.446575
73153,2023-12-04,2.0,1.20,1.71,2.34,0.000000,0.000000,124821.0,15.0,1.064334,...,-0.10972,0.10401,2.431477e+08,5.283660e+08,-0.425,0.03447,-0.18544,-0.18645,0.472222,0.452055

In [4]:
volatility = data.groupby(["ticker", "sigma"]).size().reset_index(name='counts')

# Drop the 'counts' column if you only want 'ticker' and 'sigma'
volatility = volatility.drop(columns=['counts'])
volatility

     ticker     sigma
0         A  0.263417
1        AA  0.507724
2      AADI  0.893230
3       AAL  0.367766
4       AAN  0.614387
...     ...       ...
3970   ZVIA  0.696483
3971   ZVRA  0.561204
3972    ZWS  0.270981
3973   ZYME  0.470246
3974   ZYXI  0.599988

[3975 rows x 2 columns]

In [1]:
import sklearn as sk
import matplotlib as plt
import pandas as pd


# Use read_csv() to load the CSV file into a pandas DataFrame
rnn_data = pd.read_csv('Data/partial rnn_data.csv',low_memory=False)
rnn_data.drop('Unnamed: 0', axis = 1, inplace = True)
rnn_data

,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,...,freeCashflow,operatingCashflow,earningsGrowth,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,industrySymbol,tau,tau2
0,2024-07-18,220.0,215.97,425.42,425.19,0.0,0.0,23007829.0,1.0,3.564454,...,6.199800e+10,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.023810,0.021918
1,2024-07-15,230.0,225.92,425.42,425.19,0.0,0.0,23007829.0,0.0,3.166994,...,6.199800e+10,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.035714,0.030137
2,2024-07-09,240.0,223.72,425.42,425.19,0.0,0.0,23007829.0,1.0,2.983401,...,6.199800e+10,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.051587,0.046575
3,2024-07-22,260.0,180.67,425.42,425.19,0.0,0.0,23007829.0,1.0,2.661136,...,6.199800e+10,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.015873,0.010959
4,2024-07-19,270.0,166.63,425.42,425.19,0.0,0.0,23007829.0,2.0,2.496098,...,6.199800e+10,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.019841,0.019178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278725,2024-07-17,2.5,1.90,0.00,0.00,0.0,0.0,769822.0,1.0,0.000010,...,NaN,NaN,NaN,NaN,1.00000,-2.90779,-2.910300,NaN,0.087302,0.082192
278726,2024-07-10,2.5,0.05,0.00,0.00,0.0,0.0,4611.0,6.0,0.500005,...,7.321450e+07,-5.265700e+07,NaN,52.000,-0.17556,NaN,-4.498950,NaN,0.107143,0.101370
278727,2024-05-23,0.5,0.10,2.22,3.77,0.0,0.0,20229.0,527.0,0.000010,...,-5.295625e+06,-8.944000e+06,NaN,-0.141,NaN,NaN,-41.363636,NaN,0.242063,0.232877
278728,2024-03-04,1.0,0.15,2.22,3.77,0.0,0.0,20229.0,2.0,0.000010,...,-5.295625e+06,-8.944000e+06,NaN,-0.141,NaN,NaN,-41.363636,NaN,0.472222,0.452055
278729,2024-03-04,2.5,0.03,2.22,3.77,0.0,0.0,20229.0,16.0,0.000010,...,-5.295625e+06,-8.944000e+06,NaN,-0.141,NaN,NaN,-41.363636,NaN,0.472222,0.452055

In [2]:
rnn_data.date.unique()

array(['2024-07-23', '2024-07-24', '2024-07-25', '2024-07-26'],
      dtype=object)

In [5]:
merged_df_inner = pd.merge(rnn_data, volatility, on='ticker', how='left')
merged_df_inner

,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,...,operatingCashflow,earningsGrowth,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,industrySymbol,tau,tau2,sigma
0,2024-07-18,220.0,215.97,425.42,425.19,0.0,0.0,23007829.0,1.0,3.564454,...,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.023810,0.021918,0.223118
1,2024-07-15,230.0,225.92,425.42,425.19,0.0,0.0,23007829.0,0.0,3.166994,...,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.035714,0.030137,0.223118
2,2024-07-09,240.0,223.72,425.42,425.19,0.0,0.0,23007829.0,1.0,2.983401,...,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.051587,0.046575,0.223118
3,2024-07-22,260.0,180.67,425.42,425.19,0.0,0.0,23007829.0,1.0,2.661136,...,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.015873,0.010959,0.223118
4,2024-07-19,270.0,166.63,425.42,425.19,0.0,0.0,23007829.0,2.0,2.496098,...,1.101230e+11,0.2,0.170,0.69894,0.53250,0.445880,NaN,0.019841,0.019178,0.223118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278725,2024-07-17,2.5,1.90,0.00,0.00,0.0,0.0,769822.0,1.0,0.000010,...,NaN,NaN,NaN,1.00000,-2.90779,-2.910300,NaN,0.087302,0.082192,2.099116
278726,2024-07-10,2.5,0.05,0.00,0.00,0.0,0.0,4611.0,6.0,0.500005,...,-5.265700e+07,NaN,52.000,-0.17556,NaN,-4.498950,NaN,0.107143,0.101370,2.166917
278727,2024-05-23,0.5,0.10,2.22,3.77,0.0,0.0,20229.0,527.0,0.000010,...,-8.944000e+06,NaN,-0.141,NaN,NaN,-41.363636,NaN,0.242063,0.232877,1.978739
278728,2024-03-04,1.0,0.15,2.22,3.77,0.0,0.0,20229.0,2.0,0.000010,...,-8.944000e+06,NaN,-0.141,NaN,NaN,-41.363636,NaN,0.472222,0.452055,1.978739
278729,2024-03-04,2.5,0.03,2.22,3.77,0.0,0.0,20229.0,16.0,0.000010,...,-8.944000e+06,NaN,-0.141,NaN,NaN,-41.363636,NaN,0.472222,0.452055,1.978739

In [15]:
full_rnn_data = merged_df_inner

In [16]:
full_rnn_data.date.unique()

array(['2024-07-23', '2024-07-24', '2024-07-25', '2024-07-26'],
      dtype=object)

In [17]:
full_rnn_data = full_rnn_data.sort_values(by=['ticker', 'call', 'strike'])
full_rnn_data

,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,...,operatingCashflow,earningsGrowth,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,industrySymbol,tau,tau2,sigma
153554,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,1.136723,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.071429,0.065753,0.263417
225020,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,1.602541,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.071429,0.065753,0.263417
17143,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,0.871095,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.301587,0.290411,0.263417
84912,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,0.912110,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.301587,0.290411,0.263417
153555,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,0.949219,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.301587,0.290411,0.263417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273310,2024-05-15,17.5,0.35,8.90,8.96,0.0,0.0,1034596.0,109.0,0.500005,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.265873,0.254795,0.599988
62593,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,1.830079,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988
130334,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,1.894532,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988
201337,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,1.925782,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988
273311,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,2.339848,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988

In [18]:
full_rnn_data.to_csv('Data/full_rnn_data.csv')

In [33]:
import sklearn as sk
import matplotlib as plt
import pandas as pd


# Use read_csv() to load the CSV file into a pandas DataFrame
rnn_data = pd.read_csv('Data/full_rnn_data.csv',low_memory=False)
rnn_data.drop('Unnamed: 0', axis = 1, inplace = True)
rnn_data

,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,...,operatingCashflow,earningsGrowth,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,industrySymbol,tau,tau2,sigma
0,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,1.136723,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.071429,0.065753,0.263417
1,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,1.602541,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.071429,0.065753,0.263417
2,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,0.871095,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.301587,0.290411,0.263417
3,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,0.912110,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.301587,0.290411,0.263417
4,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,0.949219,...,1.896000e+09,0.029,-0.084,0.50630,0.24458,0.23713,NaN,0.301587,0.290411,0.263417
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278725,2024-05-15,17.5,0.35,8.90,8.96,0.0,0.0,1034596.0,109.0,0.500005,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.265873,0.254795,0.599988
278726,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,1.830079,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988
278727,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,1.894532,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988
278728,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,1.925782,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988
278729,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,2.339848,...,1.828300e+07,-0.574,0.110,0.79998,0.07865,0.04462,NaN,0.464286,0.446575,0.599988

In [41]:
old_data_columns = data.columns
old_data_columns

Index(['lastTradeDate', 'strike', 'price', 'bid', 'ask', 'change',
       'percentChange', 'volume', 'openInterest', 'sigma',
       ...
       'returnOnAssets', 'returnOnEquity', 'freeCashflow', 'operatingCashflow',
       'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins',
       'tau', 'tau2'],
      dtype='object', length=114)

In [40]:
rnn_data_columns = rnn_data.columns
rnn_data_columns

Index(['lastTradeDate', 'strike', 'price', 'bid', 'ask', 'change',
       'percentChange', 'volume', 'openInterest', 'impliedVolatility',
       ...
       'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins',
       'ebitdaMargins', 'operatingMargins', 'industrySymbol', 'tau', 'tau2',
       'sigma'],
      dtype='object', length=136)

In [42]:
rnn_data = rnn_data.rename(columns={'lastPrice': 'price'})

In [43]:
difference = [item for item in rnn_data_columns if item not in old_data_columns]
difference.remove('date')
difference

['impliedVolatility',
 'contractSize',
 'zip',
 'industryKey',
 'industryDisp',
 'sectorKey',
 'sectorDisp',
 'governanceEpochDate',
 'compensationAsOfEpochDate',
 'trailingPE',
 'earningsQuarterlyGrowth',
 '52WeekChange',
 'SandP52WeekChange',
 'quoteType',
 'timeZoneFullName',
 'uuid',
 'messageBoardId',
 'gmtOffSetMilliseconds',
 'currentPrice',
 'earningsGrowth',
 'industrySymbol']

In [44]:
rnn_data.drop(difference,axis = 1, inplace=True)

In [48]:
column_order = old_data_columns.insert(0, "date")
column_order

Index(['date', 'lastTradeDate', 'strike', 'price', 'bid', 'ask', 'change',
       'percentChange', 'volume', 'openInterest',
       ...
       'returnOnAssets', 'returnOnEquity', 'freeCashflow', 'operatingCashflow',
       'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins',
       'tau', 'tau2'],
      dtype='object', length=115)

In [49]:
rnn_data= rnn_data[column_order]
rnn_data

,date,lastTradeDate,strike,price,bid,ask,change,percentChange,volume,openInterest,...,returnOnAssets,returnOnEquity,freeCashflow,operatingCashflow,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,tau,tau2
0,2024-07-25,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.071429,0.065753
1,2024-07-26,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.071429,0.065753
2,2024-07-23,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.301587,0.290411
3,2024-07-24,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.301587,0.290411
4,2024-07-25,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.301587,0.290411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278725,2024-07-26,2024-05-15,17.5,0.35,8.90,8.96,0.0,0.0,1034596.0,109.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.265873,0.254795
278726,2024-07-23,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575
278727,2024-07-24,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575
278728,2024-07-25,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575
278729,2024-07-26,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575

In [50]:
rnn_data.to_csv('Data/full_rnn_data_2.csv')

In [88]:
import pandas as pd 

data = pd.read_csv('Data/full_rnn_data_2.csv')
data.drop('Unnamed: 0', axis = 1, inplace= True)
data.drop('state', axis = 1, inplace= True)
data

C:\Users\domen\AppData\Local\Temp\ipykernel_17604\1768217909.py:3: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('Data/full_rnn_data_2.csv')

,date,lastTradeDate,strike,price,bid,ask,change,percentChange,volume,openInterest,...,returnOnAssets,returnOnEquity,freeCashflow,operatingCashflow,revenueGrowth,grossMargins,ebitdaMargins,operatingMargins,tau,tau2
0,2024-07-25,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.071429,0.065753
1,2024-07-26,2024-07-23,70.0,0.18,137.05,137.12,0.0,0.0,1717668.0,2.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.071429,0.065753
2,2024-07-23,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.301587,0.290411
3,2024-07-24,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.301587,0.290411
4,2024-07-25,2024-05-02,85.0,0.10,137.05,137.12,0.0,0.0,1717668.0,16.0,...,0.07818,0.20709,924249984.0,1.896000e+09,-0.084,0.50630,0.24458,0.23713,0.301587,0.290411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278725,2024-07-26,2024-05-15,17.5,0.35,8.90,8.96,0.0,0.0,1034596.0,109.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.265873,0.254795
278726,2024-07-23,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575
278727,2024-07-24,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575
278728,2024-07-25,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575
278729,2024-07-26,2024-03-06,20.0,0.50,8.90,8.96,0.0,0.0,1034596.0,2.0,...,0.04797,0.12696,19597876.0,1.828300e+07,0.110,0.79998,0.07865,0.04462,0.464286,0.446575

In [91]:
data.recommendationKey.unique()

array(['buy', 'hold', 'none', 'strong_buy', 'underperform', 'sell', nan],
      dtype=object)

In [112]:
missing_percentage = (data.isnull().sum() / len(data)) * 100
missing = missing_percentage[(missing_percentage > 0)]
to_fill_median = missing.index.tolist()

# List of columns to remove
columns_to_remove = ['stock', 'address1', 'city', 'country', 'industry', 'sector','recommendationKey']

# Remove each column from the list
for col in columns_to_remove:
    if col in to_fill_median:  # Check if the column is in the list
        to_fill_median.remove(col)

to_fill_median

[]

In [113]:
columns_to_remove.remove('stock')

In [114]:
columns_to_remove

['address1', 'city', 'country', 'industry', 'sector', 'recommendationKey']

In [97]:
column_median = data[to_fill_median].median()
data[to_fill_median] = data[to_fill_median].fillna(column_median)

In [115]:
data = data.drop(columns=columns_to_remove)

In [116]:
missing_percentage = (data.isnull().sum() / len(data)) * 100
missing = missing_percentage[(missing_percentage > 0)]
missing

stock    0.00574
dtype: float64

In [117]:
data.to_csv('Data/full_rnn_data_2.csv')